#!/bin/sh

required_packages='build-essential cmake python-dev python3-dev exuberant-ctags'

is_installed() {
    package_name=$1
    installed=$(dpkg-query -W -f='${Status}' ${package_name} 2>/dev/null | grep -c "ok installed")
    if [ $installed -ne 0 ]; then
        return 0;
    else
        return 1;
    fi
}

install_missing_packages() {
    for package in "$@";
    do
        if ! is_installed $package; then
            echo -n 'Required package '$package' is not installed. Do you want to install it? [Y/n] '
            read -n 1 response </dev/tty
            echo ''
            if [[ $response =~ ^(y|Y)$ ]] ; then
                sudo apt-get install $package
            else
                echo 'Installation aborted'
                exit 1
            fi
        fi
    done
    return 0
}

main() {
    # Check if config already exists
    if [ -d ~/.vim ] || [ -f ~/.vimrc ];
    then
        echo 'Found existing vim config or your machine. Please remove ~/.vim and ~/.vimrc' before proceeding.
        exit 1
    fi

    # Install missing required packages if there are any.
    # User will be promped before any installation is done.
    install_missing_packages $required_packages

    git clone --recursive git@github.com:axeldavid/vim-config.git ~/.vim
    ln -s ~/.vim/vimrc ~/.vimrc
    vim +PluginInstall +qall

    # Set ctags config if it doesn't exist already
    if [ ! -f ~/.ctags ]; then
        ln -s ~/.vim/ctags ~/.ctags
    else
        echo "Found existin ctags config. Not overriding"
    fi

    # Set tern config if it doesn't exist already
    if [ ! -f ~/.tern-config ]; then
        ln -s ~/.vim/tern-config ~/.tern-config
    else
        echo "Found existing tern config. Not overriding."
    fi

    # Install tern completer for YouCompleteMe vim plugin
    ~/.vim/bundle/YouCompleteMe/install.py --tern-completer
}

main
