#!/bin/bash

required_packages=(build-essential cmake python-dev python3-dev exuberant-ctags)

is_installed() {
    package_name = $1
    installed = $(dpkg-query -W -f='${Status}' ${package_name} 2>/dev/null | grep -c "ok installed")
    if [ installed ] ; then
        return 0;
    else
        return 1;
    fi
}

install_missing_packages() {
    for package in required_packages
    do
        if [ ! is_installed $package ] ; then
            echo 'Required package '$package' is not installed. Do you want to install it? [Y/n]'
            read -n 1 response
            if [[ $response =~ ^(y|Y)$ ]] ; then
                sudo apt-get install $package
            else
                echo 'Installation aborted'
                return 1
            fi
        fi
    done
    return 0
}

main() {
    # Check if config already exists
    if [ -d ~/.vim ] || [ -f ~/.vimrc ]; then
        echo 'Found existing vim config or your machine. Please remove ~/.vim and ~/.vimrc' before proceeding.
        exit 1
    fi

    if [ ! install_missing_packages ] ; then
        exit 1
    fi

    git clone --recursive git@github.com:axeldavid/vim-config.git ~/.vim
    ln -s ~/.vim/vimrc ~/.vimrc
    vim +PluginInstall +qall

    if [ ! -f ~/.ctags ]; then
        ln -s ~/.vim/ctags ~/.ctags
    fi

    if [ ! -f ~/.tern-config ]; then
        ln -s ~/.vim/tern-config ~/.tern-config
    fi
}

main
